DROP TABLE "IBYS"."GIS_WATERTANK" CASCADE CONSTRAINTS PURGE;
DROP TABLE "IBYS"."GIS_VALVE" CASCADE CONSTRAINTS PURGE;
DROP TABLE "IBYS"."GIS_PIPE" CASCADE CONSTRAINTS PURGE;
DROP TABLE "IBYS"."GIS_LINE" CASCADE CONSTRAINTS PURGE;
DROP TABLE "IBYS"."GIS_DISTRICT" CASCADE CONSTRAINTS PURGE;
DROP TABLE "IBYS"."GIS_MATERIAL" CASCADE CONSTRAINTS PURGE;
DROP TABLE "IBYS"."GIS_HYDRANT" CASCADE CONSTRAINTS PURGE;
DROP TABLE "IBYS"."GIS_PIPE_VALVE" CASCADE CONSTRAINTS PURGE;
DROP TABLE "IBYS"."GIS_VALVE_PARENTVALVE" CASCADE CONSTRAINTS PURGE;
DROP TABLE "IBYS"."GIS_ELEMENTSUBTYPE" CASCADE CONSTRAINTS PURGE;
DROP TABLE "IBYS"."GIS_INFRASTRUCTUREPOINTTYPE" CASCADE CONSTRAINTS PURGE;
DROP TABLE "IBYS"."GIS_NETWORKELEMENT" CASCADE CONSTRAINTS PURGE;
DROP TABLE "IBYS"."GIS_FACILITY" CASCADE CONSTRAINTS PURGE;
DROP TABLE "IBYS"."GIS_SUBSCRIBERSERVICEPOINT" CASCADE CONSTRAINTS PURGE;
DROP TABLE "IBYS"."GIS_SUBSCRIBERBUILDING" CASCADE CONSTRAINTS PURGE;
DROP TABLE "IBYS"."GIS_SUBSCRIBERPOINT" CASCADE CONSTRAINTS PURGE;
DROP TABLE "IBYS"."GIS_JUNCTION" CASCADE CONSTRAINTS PURGE;
DROP TABLE "IBYS"."GIS_CONNECTIVITY" CASCADE CONSTRAINTS PURGE;
DROP TABLE "IBYS"."ABYS_SUBSCRIBERCONSUMPTION" CASCADE CONSTRAINTS PURGE;


DELETE FROM USER_SDO_GEOM_METADATA;

INSERT INTO user_sdo_geom_metadata
VALUES ('GIS_VALVE', 'GEOM', SDO_DIM_ARRAY(SDO_DIM_ELEMENT('', -180, 180, 0.005), SDO_DIM_ELEMENT('', -90, 90, 0.005)),
        NULL);
CREATE INDEX GISVALVE_GEOM_SPATIAL_INDX
  ON GIS_VALVE (GEOM) INDEXTYPE IS mdsys.spatial_index;

INSERT INTO user_sdo_geom_metadata
VALUES
  ('GIS_WATERTANK', 'GEOM', SDO_DIM_ARRAY(SDO_DIM_ELEMENT('', -180, 180, 0.005), SDO_DIM_ELEMENT('', -90, 90, 0.005)),
   NULL);
CREATE INDEX GISWATERTANK_GEOM_SPATIAL_INDX
  ON GIS_WATERTANK (GEOM) INDEXTYPE IS mdsys.spatial_index;

INSERT INTO user_sdo_geom_metadata
VALUES ('GIS_PIPE', 'GEOM', SDO_DIM_ARRAY(SDO_DIM_ELEMENT('', -180, 180, 0.005), SDO_DIM_ELEMENT('', -90, 90, 0.005)),
        NULL);
CREATE INDEX GISPIPE_GEOM_SPATIAL_INDX
  ON GIS_PIPE (GEOM) INDEXTYPE IS mdsys.spatial_index;

INSERT INTO user_sdo_geom_metadata
VALUES
  ('GIS_HYDRANT', 'GEOM', SDO_DIM_ARRAY(SDO_DIM_ELEMENT('', -180, 180, 0.005), SDO_DIM_ELEMENT('', -90, 90, 0.005)),
   NULL);
CREATE INDEX GISHYDRANT_GEOM_SPATIAL_INDX
  ON GIS_HYDRANT (GEOM) INDEXTYPE IS mdsys.spatial_index;

INSERT INTO user_sdo_geom_metadata
VALUES
  ('GIS_DISTRICT', 'GEOM', SDO_DIM_ARRAY(SDO_DIM_ELEMENT('', -180, 180, 0.005), SDO_DIM_ELEMENT('', -90, 90, 0.005)),
   41100);
CREATE INDEX GISDISTRICT_GEOM_SPATIAL_INDX
  ON GIS_DISTRICT (GEOM) INDEXTYPE IS mdsys.spatial_index;

INSERT INTO user_sdo_geom_metadata
VALUES
  ('GIS_FACILITY', 'GEOM', SDO_DIM_ARRAY(SDO_DIM_ELEMENT('', -180, 180, 0.005), SDO_DIM_ELEMENT('', -90, 90, 0.005)),
   NULL);
CREATE INDEX GISFACILITY_GEOM_SPATIAL_INDX
  ON GIS_FACILITY (GEOM) INDEXTYPE IS mdsys.spatial_index;

--dma abone noktası eşleşme kontrolü

--500
SELECT COUNT(1)
FROM GIS_CONNECTIVITY
WHERE GIS_FACILITY_ID =
      (SELECT ID
       FROM GIS_FACILITY
       WHERE FACILITY_ID = 'DMA4-02');

--385
SELECT COUNT(1)
FROM GIS_CONNECTIVITY
WHERE GIS_FACILITY_ID =
      (SELECT ID
       FROM GIS_FACILITY
       WHERE FACILITY_ID = 'DMA4-01');

--453
SELECT COUNT(1)
FROM GIS_CONNECTIVITY
WHERE GIS_FACILITY_ID =
      (SELECT ID
       FROM GIS_FACILITY
       WHERE FACILITY_ID = 'DMA2-05');